// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

#include <iostream>

using namespace std;

int main()
{
    int n_0 = 0, n_1 = 0, n_2 = 1, sum = 0;

    while(n_2 < 4000000)
    {
        n_0 = n_1;
        n_1 = n_2;
        n_2 = n_0 + n_1;

        if(n_2 < 4000000 && n_2 % 2 == 0)
        {
            sum += n_2;
        }
    }

    cout << "The sum of the even-valued terms in a Fibonacci sequence between 1 and four million is:" << endl;
    cout << sum << endl;

    return 0;
}
